/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.egoavara.throwifperf;

import org.openjdk.jmh.annotations.Benchmark;
import org.openjdk.jmh.annotations.BenchmarkMode;
import org.openjdk.jmh.annotations.Fork;
import org.openjdk.jmh.annotations.Mode;
import org.openjdk.jmh.annotations.OutputTimeUnit;

import static org.junit.Assert.*;

import java.util.concurrent.TimeUnit;

@BenchmarkMode(Mode.AverageTime)
@OutputTimeUnit(TimeUnit.MILLISECONDS)
@Fork(value = 2, jvmArgs= {"-Xms4G", "-Xmx4G"})
public class AppTest {
    public static final int MAX_ITER = 1000000;

    @Benchmark
    public void checkWithThrowString() {
        App classUnderTest = new App();
        for (int i = 0; i < MAX_ITER; i++) {
            classUnderTest.checkWithThrow("hello");
        }
    }

    @Benchmark
    public void checkWithThrowNumber() {
        App classUnderTest = new App();
        for (int i = 0; i < MAX_ITER; i++) {
            classUnderTest.checkWithThrow("1");
        }
    }

    @Benchmark
    public void checkWithComplexRegexString() {
        App classUnderTest = new App();
        for (int i = 0; i < MAX_ITER; i++) {
            classUnderTest.checkWithComplexRegex("hello");
        }
    }

    @Benchmark
    public void checkWithComplexRegexNumber() {
        App classUnderTest = new App();
        for (int i = 0; i < MAX_ITER; i++) {
            classUnderTest.checkWithComplexRegex("1");
        }
    }

    @Benchmark
    public void checkWithSimpleRegexString() {
        App classUnderTest = new App();
        for (int i = 0; i < MAX_ITER; i++) {
            classUnderTest.checkWithSimpleRegex("hello");
        }
    }

    @Benchmark
    public void checkWithSimpleRegexNumber() {
        App classUnderTest = new App();
        for (int i = 0; i < MAX_ITER; i++) {
            classUnderTest.checkWithSimpleRegex("1");
        }
    }
}
